export const counterMap: Record<string, string[]> = {
  // --- 돌격 (Tank) 영웅 ---
  "dva": ["zarya", "symmetra", "mei"],
  "doomfist": ["sombra", "roadhog", "ana"],
  "junker-queen": ["kiriko", "ana", "zenyatta"],
  "mauga": ["ana", "sigma", "dva"],
  "orisa": ["zarya", "sigma", "hanzo"],
  "ramattra": ["bastion", "reaper", "roadhog"],
  "reinhardt": ["bastion", "reaper", "ramattra"],
  "roadhog": ["ana", "orisa", "reaper"],
  "sigma": ["zarya", "symmetra", "winston"],
  "winston": ["reaper", "bastion", "roadhog"],
  "wrecking-ball": ["sombra", "roadhog", "ana"],
  "zarya": ["bastion", "reaper", "venture"],
  "hazard": ["ana", "cassidy", "reaper"],
  "domina": ["sombra", "bastion", "ramattra"],

  // --- 공격 (Damage) 영웅 ---
  "ashe": ["widowmaker", "hanzo", "genji"],
  "bastion": ["hanzo", "genji", "tracer"],
  "cassidy": ["hanzo", "widowmaker", "ashe"],
  "echo": ["widowmaker", "ashe", "cassidy"],
  "genji": ["winston", "zarya", "symmetra"],
  "hanzo": ["genji", "winston", "sombra"],
  "junkrat": ["pharah", "echo", "widowmaker"],
  "mei": ["pharah", "echo", "sierra"],
  "pharah": ["widowmaker", "soldier-76", "ashe"],
  "reaper": ["pharah", "echo", "ashe"],
  "sojourn": ["widowmaker", "hanzo", "genji"],
  "soldier-76": ["widowmaker", "hanzo", "tracer"],
  "sombra": ["winston", "zarya", "brigitte"],
  "symmetra": ["pharah", "echo", "widowmaker"],
  "torbjorn": ["hanzo", "widowmaker", "pharah"],
  "tracer": ["torbjorn", "brigitte", "cassidy"],
  "widowmaker": ["genji", "winston", "sombra"],
  "venture": ["pharah", "echo", "cassidy"],
  "freja": ["genji", "tracer", "dva"],
  "vendetta": ["reaper", "mei", "ana"],
  "emre": ["sombra", "hanzo", "widowmaker"],
  "anran": ["sigma", "cassidy", "winston"],
  "sierra": ["tracer", "genji", "sombra"],

  // --- 지원 (Support) 영웅 ---
  "ana": ["genji", "tracer", "sombra"],
  "baptiste": ["sombra", "genji", "roadhog"],
  "brigitte": ["pharah", "echo", "hanzo"],
  "illari": ["genji", "tracer", "dva"],
  "kiriko": ["tracer", "sombra", "genji"],
  "lifeweaver": ["sombra", "tracer", "genji"],
  "lucio": ["moira", "symmetra", "mei"],
  "mercy": ["winston", "genji", "tracer"],
  "moira": ["dva", "ana", "widowmaker"],
  "zenyatta": ["sombra", "tracer", "genji"],
  "juno": ["sombra", "dva", "cassidy"],
  "wuyang": ["sombra", "tracer", "widowmaker"],
  "mizuki": ["sombra", "genji", "winston"],
  "jetpack-cat": ["soldier-76", "ashe", "widowmaker"]
};

export const heroNameMap: Record<string, string> = {
  "ana": "아나",
  "anran": "안란",
  "ashe": "애쉬",
  "baptiste": "바티스트",
  "bastion": "바스티온",
  "brigitte": "브리기테",
  "cassidy": "캐서디",
  "domina": "도미나",
  "doomfist": "둠피스트",
  "dva": "디바",
  "echo": "에코",
  "emre": "엠레",
  "freja": "프레이야",
  "genji": "겐지",
  "hanzo": "한조",
  "hazard": "해저드",
  "illari": "일리아리",
  "jetpack-cat": "제트팩 캣",
  "junker-queen": "정커퀸",
  "junkrat": "정크랫",
  "juno": "주노",
  "kiriko": "키리코",
  "lifeweaver": "라이프위버",
  "lucio": "루시우",
  "mauga": "마우가",
  "mei": "메이",
  "mercy": "메르시",
  "mizuki": "미즈키",
  "moira": "모이라",
  "orisa": "오리사",
  "pharah": "파라",
  "ramattra": "라마트라",
  "reaper": "리퍼",
  "reinhardt": "라인하르트",
  "roadhog": "로드호그",
  "sierra": "시에라",
  "sigma": "시그마",
  "sojourn": "소전",
  "soldier-76": "솔저: 76",
  "sombra": "솜브라",
  "symmetra": "시메트라",
  "torbjorn": "토르비욘",
  "tracer": "트레이서",
  "vendetta": "벤데타",
  "venture": "벤처",
  "widowmaker": "위도우메이커",
  "winston": "윈스턴",
  "wrecking-ball": "레킹볼",
  "wuyang": "우양",
  "zarya": "자리야",
  "zenyatta": "젠야타"
};
